path: \Mestrado\FotosSubstacoes\mission1\data  # dataset root dir
train: \Mestrado\FotosSubstacoes\mission1\data\images # train images (relative to 'path') 128 images
val: \Mestrado\FotosSubstacoes\mission1\data\images  # val images (relative to 'path') 128 images
#test:  # test images (optional)

# Classes
names:
  0:
  1:
  2:
  3:
  4:
  5:
  6:
  7:
  8:
  9:
  10:
  11:
  12:
  13:
  14:
  15: reator